language: ruby
rvm:
  - 2.1.2
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database corgi_test' -U postgres
notifications:
  email: false
services:
  - redis-server
